-- Programmers SQL GROUP BY problem 4
-- https://programmers.co.kr/learn/courses/30/lessons/59413
SELECT HOUR, NVL(co, 0) AS COUNT
FROM (SELECT TO_CHAR(TO_DATE('00'+ LEVEL -1,'HH24')  , 'HH24') AS HOUR
    FROM dual 
    CONNECT BY LEVEL <= 24) LEFT OUTER JOIN (
      SELECT TO_CHAR(DATETIME, 'HH24') AS ANI_HOUR , COUNT(DATETIME) AS co
      FROM ANIMAL_OUTS
      GROUP BY TO_CHAR(DATETIME, 'HH24'))
ON HOUR = ANI_HOUR
ORDER BY HOUR
